### PR TITLE
Remove FR from built languages (2.03)

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**

### CODE REVIEW

**Comment by andylolz** [comment]
This is a breaking change, isn't it? I have a feeling it'll remove a bunch of stuff (e.g. FR codelists?)

**Comment by samuele-mattiuzzo** [comment]
I assumed the same yes, but after re-generating the docs, the french narratives still seem to be there for the codelists 

```
<name>
    <narrative>Planned start</narrative>
    <narrative xml:lang="fr">Début prévu</narrative>
</name>
```

unless you're referring to something else that I'm not aware of? I have been checking with the BAs and this seems to be where we have the fr versions.

If it's just about having `codelist-management.rst` and `codelist-api.rst` in the [IATI-Extra-Documentation](https://github.com/IATI/IATI-Extra-Documentation/tree/version-2.03/fr) and have them point back at the `../en/<file>` equivalent, then the original issue should have been raised in the other repo.

As the team is still fairly new, we're all still learning how everything is tangled together :)

**Comment by andylolz** [comment]
> I assumed the same yes, but after re-generating the docs, the french narratives still seem to be there for the codelists

The XML definitely won’t be affected, since it’s just pulled straight through from the codelist repos.

I had _thought_ the JSON and CSV would be affected ([e.g.](http://reference.iatistandard.org/203/codelists/downloads/clv3/json/fr/AidType.json)), but in fact I think that’s determined by the language declaration here:
https://github.com/IATI/IATI-Codelists/blob/0e1e79af/gen.py#L6

…so it’s probably fine.

> As the team is still fairly new, we're all still learning how everything is tangled together :)

I’ve got a pretty good understanding of how lots of this stuff works ([e.g.](https://discuss.iatistandard.org/t/show-iati-multilingual-iati-standard-site/1266)). If I can help at all, please drop me an email and let me know.

**Comment by samuele-mattiuzzo** [comment]
Yeah I did post the XML snippet as an example, but have been going through other formats as well and all seems to check out! John won't be back till next week to review these anyway, so if I find something that breaks before then I'll update them

Thanks for the offer, will deffo take you up on that (long overdue email contact anyway ;) )

**Comment by andylolz** [comment]
> If it's just about having `codelist-management.rst` and `codelist-api.rst` in the [IATI-Extra-Documentation](https://github.com/IATI/IATI-Extra-Documentation/tree/version-2.03/fr) and have them point back at the `../en/<file>` equivalent, then the original issue should have been raised in the other repo.

Ha! Just realised you’re referring to #144, which I have little recollection of! But I’ll put my trust in past Andy that the advice was good :)

**Comment by samuele-mattiuzzo** [comment]
> But I’ll put my trust in past Andy that the advice was good :)

I wish I could trust past-Sam from yesterday :P

**Review by Ocre42 — APPROVED** [review]
Donezo!

**Pull request merged**
