### PR TITLE
Fix `narrative/@xml:lang` by using base complex type instead of the first complex type. (v2.02)

### PR DESCRIPTION
**Pull request by Ocre42**
Addresses issue #228 for version 2.02

### CODE REVIEW

**Review by samuele-mattiuzzo — APPROVED** [review]

**Comment by andylolz** [comment]
Oh… Nice spot!

I guess I completely missed this – apologies.

**Comment by andylolz** [comment]
+1 this is a good change… But I don’t see how it relates to #228… That is: I tested, and #228 already seems to be fixed prior to this change?

I wonder if you’re trying to fix an issue on the deployed version…? Is it possible your deployment script is missing a `git submodule update` somewhere?

**Comment by Ocre42** [comment]
It was fixed in version 2.03 but not the other versions, this should fix it for other versions (once it is deployed)

**Comment by andylolz** [comment]
Okay but if I revert `version-2.02` back before this change, and run `python gen.py`, it’s already fixed (i.e. I see “should”s where I should see “should”s)… So I’m wondering if there’s some other issue that’s making this appear not fixed?

**Comment by andylolz** [comment]
Just to explain… The code in this PR was added because of `documentLinkResultBase`, which only exists in v2.03. That’s presumably why it wasn’t added to other branches – because it doesn’t affect those. `xml:lang` isn’t a `complexType`, so it’s unrelated to this change. The commit message for this change (2ea0784f) says:

> Some complexType elements extend from other complexType elements - for example `documentLinkResultBase`, which extends from `documentLinkBase` in v2.03. Previously, the code did not support such extensions. This commit enables the generation process to traverse one step up extension tree and obtains the child elements of the base.

My point here is mostly moot, because I agree with you that this is a good change. I’m just mentioning it because if you’re finding #228 isn’t fixed for all versions, then that’s a red flag that something else is wrong (possibly a submodule issue? I don’t know) and this PR won’t address it.

**Pull request merged**
