### PR TITLE
Show withdrawn status in codelists

### PR DESCRIPTION
**Pull request by Ocre42**
Addressing [#142](https://github.com/IATI/IATI-Standard-SSOT/issues/142), and displays them as follows: 
withdrawn

Currently has placeholder text on the headings, copy to be decided by BAs after discussion.

### CODE REVIEW

**Comment by andylolz** [comment]
Does this replace #175?

**Comment by Ocre42** [comment]
Requires [PR #222 on IATI-Websites](https://github.com/IATI/IATI-Websites/pull/222)

**Comment by Ocre42** [comment]
> Does this replace #175?

It still needs some cleanup but yes it would

**Comment by andylolz** [comment]
Ah, okay. Well, the styling on this version definitely looks much nicer.

But was there anything fundamentally wrong with #175? I’ve ticked “allow edits from maintainers” on most (maybe all?) of my existing PRs to IATI repos, so do feel free to continue work by pushing to my existing PRs.

**Comment by Ocre42** [comment]
It's my bad @andylolz, I started working on this whilst travelling so I didn't go in depth into the existing PRs, looking at them now I could make the merge on your PR when moving forwards once I get confirmation for the copy for withdrawn status from the BAs

**Comment by andylolz** [comment]
Ah, okay – thank you @Ocre42.

The extra bits you’ve added (styling; conditional link to changelog) are great improvements imo.

Most of all I’m pleased that this is moving forward – that is really great!

**Pull request closed without merging**
