### PR TITLE
Track relevant submodule branches (v2.03)

### LINKED ISSUE #2: Look into submodules that follow a branch
These look useful for the SSOT, but require some more investigation before we start using them.

### LINKED ISSUE #168: update_submodules.sh doesn’t scrap local commits (it should)
Before pulling each submodule, it’s important to do a `git reset --hard origin/version-$version`. Otherwise, local commits can end up being referenced that don’t exist on the remote. I suspect that may have been the cause of #165.

It also wouldn’t hurt to throw away local changes with `git checkout -- . && git clean -fd` (or similar). This should ensure the `git pull` succeeds.

---

Also, I notice update_submodules.sh is different on every SSOT version branch. Surely this is problematic?

I wonder if you’d be better off moving this update script into its own branch, or even its own repo, and forcing it to clone a fresh IATI-Standard-SSOT every time. This is the foolproof method of ensuring nothing weird happens. I’d also really recommend using [hub](https://github.com/github/hub) because it’ll send all the pull requests for you.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #2.
Also fixes #168.

It looks like [there’s a bit of the update_submodules script](https://github.com/IATI/IATI-Standard-SSOT/blob/666472c8df14d4b5bb85b57437b71626782d1334/update_submodules.sh#L17-L32) that currently updates each submodule individually. But if you specify a branch, git will do this natively.

### CODE REVIEW

**Comment by andylolz** [comment]
@Bjwebb I know it was more than 4 years ago, but… On #2, do you remember what you meant by this:

> […] but require some more investigation before we start using them

Have you used submodule branch tracking since? Is it indeed a good and useful thing?

**Comment by Bjwebb** [comment]
> On #2, do you remember what you meant by this: but require some more investigation before we start using them

I think I just meant checking that the behaviour is as expected,¸and working out what commands to run.

> Have you used submodule branch tracking since?

No.

**Comment by andylolz** [comment]
I wonder (though I haven’t found it yet) if there’s the equivalent of @requires but for submodule branch tracking. It seems like that could be very helpful here (i.e. auto-send PRs when component submodules update).

**Comment by dalepotter** [comment]
This looks good in local testing, but I'm reluctant to run the script since the new data in `.gitmodules` would only exist for the v2.03 version - I can look to replicate the `.gitmodules` for other versions this coming Monday, which will enable recent changes to IATI-Extra-Documentation to be made an 'official' part of the SSOT, and therefore regenerated on the website.

Alternatively - if others have capacity - we would welcome pull requests to do complete this (for the `version-1.04`, `version-1.05`, `version-2.01` and `version-2.02` branches), which would enable recent changes to be merged and the documentation site redeployed before the end of this week.

**Comment by andylolz** [comment]
> Alternatively - others have capacity - we would welcome pull requests to do complete this (for the `version-1.04`, `version-1.05`, `version-2.01` and `version-2.02` branches), which would enable recent changes to be merged and the documentation site redeployed before the end of this week.

^^ @dalepotter: Great! I’ve sent those PRs. Where update_submodules.sh was present I’ve removed it (except on `version-2.03`), with a short explanation in the relevant PRs.

**Comment by andylolz** [comment]
I’ve made a couple more small changes to update_submodules.sh, to try and make it a bit more stable. It’s a bit difficult to handle all cases (although there are probably clever git ways to do it).

As mentioned in #168, my preferred option would be to use a separate tool to make these updates, that checks out clean versions of each branch from the remote. That would help sidestep any weird git pitfalls (e.g. local changes; local commits; untracked files etc).

**Review by dalepotter — APPROVED** [review]
Tested changed commands locally and works.

**Pull request merged**
