### PR TITLE
Refactoring the SSOT (Beta version, stable)

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**
- This feature branch has been created off `version-2.03` but, in its current state, is version-agnostic (as we will benefit from this)

- All automation (most of it, at this stage) is done via `Makefile` and scripts, to avoid leaving human error too much space

- Readme has been updated to reflect the new changes

- No more git submodules, hence why this has not been requested as a merge into the main branch straight away; I'm afraid before pushing this forward, we'll have to see what the community thinks. Hopefully, nobody's using the SSOT's repo as a shortcut for other parts of the Standard

This PR is to get the work back into the main IATI world now that most of it has been carried on and works properly (can build, can run, can switch versions etc), so that I can deal with conflicts and we can keep the branch up-to-date with whatever change we introduce in `version-2.03` till it gets decided if this is a route we can follow properly or not

### CODE REVIEW

**Review by Ocre42 — DISMISSED** [review]
approving to merge into feature branch, then work from within the repo itself 
Edit: Need to update travis to use new build process

**Comment by samuele-mattiuzzo** [comment]
Forgot to update Travis obviously :/ Will make a move towards home and finish this between this evening and tomorrow morning

**Comment by andylolz** [comment]
This is **SO COOL** :clap: :clap: :clap:

**Comment by samuele-mattiuzzo** [comment]
> This is **SO COOL** 👏 👏 👏

Now let's only hope that this repository was not really used by anyone so that moving away from git sumobdules does not impact anyone. My concern, as I stated above, is that this repo was intended/used as a shortcut to access the Codelist/Rulesets/Schema for `version-xxx` of the standard (and I do seriously hope that wasn't the case); I'm looking forward to the day this repo will just have a `live` / `master` branch and we can stop fixing everything 6 times!

**Comment by andylolz** [comment]
> I'm afraid before pushing this forward, we'll have to see what the community thinks. Hopefully, nobody's using the SSOT's repo as a shortcut for other parts of the Standard

^^ It’s possible… Because I think this was the whole idea of the SSOT (i.e. the repo itself was supposed to be the single source of truth for developers.) BUT I still really support this change as a huge step forward.

**Comment by andylolz** [comment]
> I'm looking forward to the day this repo will just have a live / master branch and we can stop fixing everything 6 times!

:100: yes exactly.

**Comment by samuele-mattiuzzo** [comment]
> i.e. the repo itself was supposed to be the single source of truth for devs

I think we can work around that by creating a `SSOT-dev-repo` that just serves the purpose of recreating the per-version grouping of each component of the Standard, just for those devs that use it as a shorcut.

**Comment by andylolz** [comment]
> I think we can work around that by creating a `SSOT-dev-repo`

Meh… I see what you mean, but… Recommend asking Discuss, and if there’s little or no appetite for this then avoid doing it. It’s just another thing for your team to maintain (however small).

**Comment by andylolz** [comment]
Totally agree with @Ocre42 re. approving to merge to feature branch on this repo 👍

**Pull request merged**
