### PR TITLE
Add script for updating IATI-Rulesets lib directory

### PR DESCRIPTION
**Pull request by nosvalds**
Keeping Dependencies Updated
============================

Currently the IATI-Rulesets Submodule XSLT transformation relies on Codelists (defined in XML) and Schemas (defined in XSD) contained in the `/lib/schemata` directory of IATI-Rulesets.

These Codelists and Schemas are actively maintained in other repositories.

Codelists

- [IATI/IATI-Codelists](https://github.com/IATI/IATI-Codelists)

- [IATI/IATI-Codelists-NonEmbedded](https://github.com/IATI/IATI-Codelists-NonEmbedded)

Schemas

- [IATI/IATI-Schemas](https://github.com/IATI/IATI-Schemas)

To ensure the IATI-Rulesets repo is up to date with the most recent changes in these repositories you can run the `update_rulesets_lib.sh` script in the [IATI SSOT](https://github.com/IATI/IATI-Standard-SSOT/) repository

This script copies the appropriate Codelists and Schemas into the appropriate `/lib/schemata` subdirectories.

You'll then need to commit to a branch and pull request into the master branch of IATI-Rulesets.

Also note that the Validator stores a copy of the IATI-Rulesets repo in it's build so results will not update in the Validator until a release has been made.

### CODE REVIEW

**Review by akmiller01 — APPROVED** [review]
:+1:

**Review by alexlydiate — APPROVED** [review]

**Comment by andylolz** [comment]
@nosvalds A couple of things aren’t clear to me here.

Firstly, when I run this script, I see a lot of errors of the form:

```
cp: directory ../IATI-Rulesets/lib/schemata/x.xx does not exist
```

The only way to resolve these is to first run something like:

```
cd IATI-Rulesets && git checkout master && cd ..
```

Secondly, it’s not clear why this script lives in the SSOT. The goal of the script is to keep codelists in the `IATI-Rulesets` repo up-to-date, so perhaps it should live in the `IATI-Rulesets` repo?

Thirdly, the SSOT still points to the old ruleset branches. Is there a plan to change this? Given the new ruleset does not use version branches, how do you plan to implement this?

**Comment by nosvalds** [comment]
Hi @andylolz ,

- That error was occurring because the script didn't originally branch from the correct branch of IATI-Rulesets before performing the copies. I've added a `git checkout master` after `cd IATI-Rulesets` to enforce this as you suggest.
  - If you'd like to review the fix PR, here it is: https://github.com/IATI/IATI-Standard-SSOT/pull/369

- I decided to put the script in SSOT because it has 2 of 3 of the repo's as submodules that I needed to pull data from to update IATI-Rulesets/lib. You're right I could have put it in IATI-Rulesets and clone'd in the other repos to copy like I do for the non-embedded codelists. I only expect to use this a handful of times before validator V2 is released and kicks this into the dustbin.

- We'd like to get rid of the versioned ruleset branches in the future and consolidate to the `master` branch style with only .xslt. However, the generation of the reference website is still dependent on the .json rules. No implementation plans yet, just in the idea stage. 

-Nik

**Comment by andylolz** [comment]
> I only expect to use this a handful of times before validator V2 is released and kicks this into the dustbin.

I don’t follow… This script is for updating validator V2, isn’t it? What needs to change to render this script redundant? (Or does validator V2 refer to a future iteration of https://iativalidator.iatistandard.org that doesn’t rely on this update script?)

> We'd like to get rid of the versioned ruleset branches in the future and consolidate to the master branch style with only .xslt

Right, yes. So my point on this was that the SSOT continues to use version branches. So I guess you’d need each version branch of the SSOT to point to the same `master` branch of the ruleset. I don’t know if there’s a nicer way to implement this.

**Comment by nosvalds** [comment]
- We're on [v1.6.3](https://github.com/IATI/IATI-Validator-Actual/releases/tag/1.6.3) of the Validator currently. As part of implementing the recommendations from the [Technical Stocktake](https://iatistandard.org/en/news/iatis-technical-stocktake/) we plan to release v2.0 of the Validator on the unified IATI infrastructure that won't rely on this script.
- Yea you raise a good point. We'll definitely need to be careful here and do it in a way that preserves the history. Overall my hope would be to simplify things if we can.

**Comment by andylolz** [comment]
Aha, okay, I see (I’d assumed [the public validator](http://validator.iatistandard.org) was v1, and therefore [the current version](https://iativalidator.iatistandard.org/) was v2.) Anyway, I’m pleased to see semver being used going forward, that’s great.

On adding scripts here, there’s a bit more discussion on this topic in #227. In fact, there’s even [an SSOT decoupling project board](https://github.com/IATI/IATI-Standard-SSOT/projects/1). My understanding from previous conversations was that the plan was for this repo to contain fewer unrelated scripts, not more.

I also appreciate this is a short-term fix, but I think it’s worth noting short-term fixes have a habit of hanging around for A Long Time.

The script itself is hacky and I think that is absolutely fine. But I don’t think it belongs in this repo. It breaks encapsulation, but moreover [this repo is public facing](https://iatistandard.org/en/guidance/developer/ssot/), so it shouldn’t _really_ be used for convenience. I actually think it’s simpler and more robust to do `git clone --recursive https://github.com/IATI/IATI-Standard-SSOT ssot` in a script on the rulesets repo, and then `rm -rf ssot` at the end of the script. That way you can guarantee the state of the worktree without needing to `clean` and `fetch` and `submodule update`.

> we plan to release v2.0 of the Validator on the unified IATI infrastructure that won't rely on this script

I’m interested to understand how this will work. Presumably validator v2 will still need to maintain a set of codelists? Wouldn’t it still need a script similar to this?

**Comment by nosvalds** [comment]
Hi Andy,

Appreciate the additional background. I'll go ahead and remove this script from the repo. 

As far as v2.0, my goal is to not have anything stored somewhere twice, as is now the case for the Codelists and Schemas that IATI-Rulesets references. My thought is to build a nightly batch in the Validator V2 that pulls the right information into its build.

We will communicate plans in the normal channels as well to keep folks updated.

Best,
Nik

**Pull request merged**
