### PR TITLE
rm docs-copy

### LINKED ISSUE #137: docs-copy should be removed and gitignored
It looks like docs-copy was added to this repo in error? It’s not in .gitmodules…

I guess it should probably be removed and gitignored.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #137.

### CODE REVIEW

**Comment by andylolz** [comment]
It’s not currently possible to `git clone --recursive` this repo, because of this bug on the `version-2.03` branch.

@dalepotter @hayfield @allthatilk Please could this PR be reviewed? Thanks

**Review by dalepotter — APPROVED** [review]
Looks good - the changes to trailing slashes should be ported to the other branches before we merge this though, for the sake of consistency... As such I'll add the appropriate label.

**Comment by andylolz** [comment]
I’ve removed changes to the gitignore, in order to get this merged. gitignore can be fixed in separate PRs.

**Comment by andylolz** [comment]
The label on this issue no longer applies – the only change here is now v2.03-specific. So this can hopefully be merged.

**Comment by dalepotter** [comment]
Thanks for this!

**Pull request merged**
